spring.application.name=ToDoList
# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# H2 DATABASE CONFIG
# ===============================
#spring.datasource.url=jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# ==============================
# POSTGRE SQL DATABASE CONFIG
# ==============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# show SQL ra console (debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# ===============================
# LOGGING (optional)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
